Validation Form
Aliahmad-karimi/My-Portfolio pull request #16
Opened 2022-07-28 00:51 UTC by Aliahmad-karimi

-add validation to all input form.
- add html validation to the name and comment input.
- -add Js validation to the email input form and its lowercase condition.

2022-07-28 01:07 UTC, vickymarz requested changes
Hi @Aliahmad-karimi , 

You have done a great job so far! 💪 👏
You still need to work on a few issues before moving on to the next project, but you're almost there!

## Top highlight 🎯

- The Pull Request is following the GitHub Flow ✅ 
- The PR title and description are professional and descriptive ✅ 
- The commit messages are meaningful ✅ 
- Linters are working properly ✅ 


## Required Changes ♻️
_Check the comments under the review._
<img src="https://media2.giphy.com/media/Jq824R93JsLwZCaiSL/giphy.gif"/>

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
- using a descriptive and clear variable name  so that your code can be easily understood 

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-07-28 01:07 UTC, victorokoroji commented on script.js
> +  });
- [ ] Kindly check the validation function again because the form still submits after displaying the email error message. Please ensure the form doesn't submit invalid data

2022-07-28 14:14 UTC, Aliahmad-karimi commented on script.js
> +  });
Dear @vickymarz I tried many condition but I did not see the result may u please just give me hint to this one.

2022-07-28 22:21 UTC, Aliahmad-karimi commented on script.js
> +  });
dear @vickymarz  I got lost in this conditioning please help me out

2022-07-28 22:46 UTC, vickymarz commented on script.js
> +  });
Sorry, I have been quite busy. Please @Aliahmad-karimi or @Tadessejemal1

2022-07-28 23:25 UTC, Aliahmad-karimi commented on script.js
> +  });
Sorry @vickymarz I did not get your point 
I tried many ways but stuck in this one

2022-07-29 10:25 UTC, sumairq approved these changes
### Hi Team , 

<img src="https://media4.giphy.com/media/BPJmthQ3YRwD6QqcVD/giphy.gif"/>

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights
✔️ Good commit history
✔️Linters are passing
✔️Very professional README
✔️Correct Github flow
✔️Descriptive PR
## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-07-29 10:31 UTC, merged